L4T Base Image
airmap/platform-sdk pull request #179
Opened 2021-10-08 21:05 UTC by jennerl

## Description
Linux4Tegra builds under emulation and takes ~5-7 hours to build, sometimes failing when the build agent loses track of the long-running build process.

As the dependencies (or their versioning) rarely changes, and because compiling the dependencies under emulation from source takes such a large percentage of the overall build time, a base image that contains all of the dependencies pre-built was an appropriate solution to the long build times and is the motivation for this PR.

## Impacted Areas in AirMap Platform SDK
List general components of the SDK that this PR will affect:

* CI system performance

2021-10-09 00:17 UTC, keith-bennett-airmap requested changes

2021-10-09 00:17 UTC, keith-bennett-airmap commented on docker/l4t/l4t
> +RUN tools/l4t/cleanup.dev.sh
```
Step 10/12 : RUN tools/l4t/cleanup.dev.sh
 ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 90fc0cd42609
/bin/sh: 1: tools/l4t/cleanup.dev.sh: Permission denied
Removing intermediate container 90fc0cd42609
The command '/bin/sh -c tools/l4t/cleanup.dev.sh' returned a non-zero code: 126
```

The script needs to be marked executable for `RUN tools/l4t/cleanup.dev.sh` to work. The base image does `chmod +x tools/l4t/*.sh`. But at the beginning of this dockerfile you do `COPY . /usr/src/app` which overwrites it with the original from the build agent's context (repository root) which isn't marked executable.

2021-10-13 20:27 UTC, jennerl commented on docker/l4t/l4t
> +RUN tools/l4t/cleanup.dev.sh
Yes, fixed in recent commits.

2021-10-13 20:28 UTC, jennerl commented
Confirmed (after manually pushing base image to container repository) that the base image is being utilized. L4T build times reduced to ~1 hour from ~6 hours.

2021-10-14 12:56 UTC, merged