misc changes to build outside of docker
airmap/platform-sdk pull request #193
Opened 2023-02-22 22:54 UTC by tim-du

## Status
**READY**

## Migrations
NO

## Description
These are the changes I had to make so I could build platform-sdk outside of the ubuntu 20.04 docker image

The boringssl change just uses a newer tag that has fixed this issue: https://github.com/nmeum/android-tools/issues/16
This is the commit that fixes it: https://boringssl.googlesource.com/boringssl/+/92c6fbfc4c44dc8462d260d836020d2b793e7804
The hash is different because we are using the github mirror.

The change to telemetry.cpp is to fix the same issue described here: https://github.com/prusa3d/PrusaSlicer/issues/3175
Seems like the boost function we were using was not intended for general use and was removed.
Here's the commit that the PrusaSlicer people made to fix it, which I followed to make my change: https://github.com/prusa3d/PrusaSlicer/commit/621b8426d3855a9b7c9c998a3d32a1adcb9fd284

The protobuf include issues just seem to be a mistake. We didn't have the protobuf_INCLUDE_DIRS in the include directories, and were using the `CONFIG` option. That's not mentioned in the protobuf cmake documentation, and removing it fixed the include issues for me.

## Testing
I made sure platform-sdk can still build in docker, and ran the unit tests and integration tests.

2023-02-23 23:00 UTC, keith-bennett-airmap requested changes

2023-02-23 23:00 UTC, keith-bennett-airmap commented on src/airmap/rest/telemetry.cpp
> +  boost::beast::detail::base64::decode((void*)&decoded_key, (const char*)&key, key.size());
No.

2023-02-23 23:57 UTC, keith-bennett-airmap requested changes

2023-02-23 23:57 UTC, keith-bennett-airmap commented on src/airmap/rest/telemetry.cpp
> +  decoded_key.resize(boost::beast::detail::base64::decode((void*)&decoded_key, (const char*)&key, key.size()).first);
Still a hard no. This code introduces remote code execution.

2023-02-23 23:58 UTC, keith-bennett-airmap commented on src/airmap/rest/telemetry.cpp
> +  decoded_key.resize(boost::beast::detail::base64::decode((void*)&decoded_key, (const char*)&key, key.size()).first);
Read [the documentation for `boost::beast::detail::base64::decode()`](https://github.com/boostorg/beast/blob/boost-1.70.0/include/boost/beast/core/detail/base64.hpp#L64-L77). Then rewrite these lines.

- Do not use any explicit casts.
- Correctly allocate a buffer of correct size.
- Correctly handle the return value.

2023-02-24 00:55 UTC, keith-bennett-airmap commented on src/airmap/rest/telemetry.cpp
> +  std::unique_ptr<unsigned char[]> decoded_key(new unsigned char[decoded_size]);
Why not `std::vector`?

2023-02-24 00:55 UTC, keith-bennett-airmap commented on src/airmap/rest/telemetry.cpp
> +  assert(res.first <= decoded_size && res.second == key.size());
We are a library to an application. It is not good behavior to `assert()` and kill an application for bad input when perhaps the application would rather handle the problem itself. Throw an exception instead.

2023-02-24 01:11 UTC, tim-du commented on src/airmap/rest/telemetry.cpp
> +  std::unique_ptr<unsigned char[]> decoded_key(new unsigned char[decoded_size]);
Didn't think of it.

2023-02-24 01:11 UTC, tim-du commented on src/airmap/rest/telemetry.cpp
> +  assert(res.first <= decoded_size && res.second == key.size());
Throwing now

2023-02-24 02:09 UTC, keith-bennett-airmap approved these changes

2023-02-24 15:54 UTC, merged